export const imageAssests = {
    abc: require('../images/ABC.png'),
    menuLine: require('../images/menu_line.png'),
    navRight: require('..//images/navRight.png'),
    pushPin: require('../images/PushPin.png'),
    warning: require('../images/Warning.png'),
    searchIcon: require('../images/searchIcon.png'),
    chartDonut: require('../images/ChartDonut.png'),
    caretUp: require('../images/CaretUp.png'),
    vector: require('../images/Vector.png'),
    gimVer: require('../images/gimVer.png'),
    list:require('../images/List.png'),
    total: require('../images/total.png'),
    order: require('../images/Oder.png'),
    diagram: require('../images/diagram.png'),
    showMore: require('../images/showMore.png'),
}